kind: pipeline
name: default

steps:
- name: docker-push
  image: plugins/docker
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
    PLUGIN_REPO: docker-registry.fruitice.fr/booster-bo
    PLUGIN_REGISTRY: docker-registry.fruitice.fr
    PLUGIN_TAG: ${DRONE_COMMIT}
  privileged: true
  when:
    branch: master
    event: push
    status: success

- name: kube-push
  image: quay.io/honestbee/drone-kubernetes
  environment:
    KUBERNETES_SERVER:
      from_secret: kubernetes_server
    KUBERNETES_CERT:
      from_secret: kubernetes_cert
    KUBERNETES_TOKEN:
      from_secret: kubernetes_token
    PLUGIN_NAMESPACE: booster
    PLUGIN_DEPLOYMENT: booster-bo
    PLUGIN_REPO: docker-registry.fruitice.fr/booster-bo
    PLUGIN_CONTAINER: booster-bo
    PLUGIN_TAG: ${DRONE_COMMIT}
  when:
    branch: master
    event: push
    status: success